# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b07a66671d32c63be9a088b67fcc326a10d8d770fc02fd7ed6d4a24ba504930b315ea805e1af7e50f227585f73324df39858c2919e2f0f6c117c66a21bd50b83

test:
  secret_key_base: c933a8c5164af33a8c9de52d8d5ebf2b952b1c6c7d283075d81d8daa12a1aa57320e43979f8748f1940d28b955c606415246f7d9daf12b7c083a7b9a6fe46b9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
